modLoader="kotlinforforge"
loaderVersion="[3,)"
license="All rights reserved"

[[mods]]
modId="pitchperfect"
version="${file.jarVersion}"
displayName="Pitch Perfect"
logoFile="logo.png"
credits="Durgerking10 for the artwork"
authors="aaronhowser1, LatvianModder"
description='''
Pitch Perfect adds instruments that change pitch depending on the angle you're aiming
'''
[[dependencies.pitchperfect]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pitchperfect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
